# permissions for end users to view mycrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycrd-viewer-role
rules:
- apiGroups:
  - demo.my.crd
  resources:
  - mycrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.my.crd
  resources:
  - mycrds/status
  verbs:
  - get
