# permissions for end users to edit mycrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycrd-editor-role
rules:
- apiGroups:
  - demo.my.crd
  resources:
  - mycrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.my.crd
  resources:
  - mycrds/status
  verbs:
  - get
